[phases.setup]
nixPkgs = ["php82", "php82Extensions.curl", "php82Extensions.mbstring", "php82Extensions.openssl", "nginx", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs"]

[phases.build]
cmds = ["mkdir -p /app/backend/public", "cp -r . /app/backend/public"]

[phases.start]
cmd = "php -S 0.0.0.0:80 index.php"
